//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPrueba.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_BODEGAEntities : DbContext
    {
        public BD_BODEGAEntities()
            : base("name=BD_BODEGAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARGO> CARGO { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<DATOS_EMPLEADO> DATOS_EMPLEADO { get; set; }
        public virtual DbSet<DETALLE_FACT> DETALLE_FACT { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<FACTURA> FACTURA { get; set; }
    
        public virtual int SP_INSERTAR_DETALLE_FACT(Nullable<int> cANTIDAD_PRODUCTO, Nullable<double> dESCUENTO, Nullable<int> fK_ID_USUARIO, Nullable<int> fK_ID_PRODUCTO, Nullable<int> fK_ID_CLIENTE)
        {
            var cANTIDAD_PRODUCTOParameter = cANTIDAD_PRODUCTO.HasValue ?
                new ObjectParameter("CANTIDAD_PRODUCTO", cANTIDAD_PRODUCTO) :
                new ObjectParameter("CANTIDAD_PRODUCTO", typeof(int));
    
            var dESCUENTOParameter = dESCUENTO.HasValue ?
                new ObjectParameter("DESCUENTO", dESCUENTO) :
                new ObjectParameter("DESCUENTO", typeof(double));
    
            var fK_ID_USUARIOParameter = fK_ID_USUARIO.HasValue ?
                new ObjectParameter("FK_ID_USUARIO", fK_ID_USUARIO) :
                new ObjectParameter("FK_ID_USUARIO", typeof(int));
    
            var fK_ID_PRODUCTOParameter = fK_ID_PRODUCTO.HasValue ?
                new ObjectParameter("FK_ID_PRODUCTO", fK_ID_PRODUCTO) :
                new ObjectParameter("FK_ID_PRODUCTO", typeof(int));
    
            var fK_ID_CLIENTEParameter = fK_ID_CLIENTE.HasValue ?
                new ObjectParameter("FK_ID_CLIENTE", fK_ID_CLIENTE) :
                new ObjectParameter("FK_ID_CLIENTE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTAR_DETALLE_FACT", cANTIDAD_PRODUCTOParameter, dESCUENTOParameter, fK_ID_USUARIOParameter, fK_ID_PRODUCTOParameter, fK_ID_CLIENTEParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_AGREGAR_FACTURA2(Nullable<System.DateTime> fECHA_FACTURA, string iNFORME_VENTA, Nullable<int> fK_CLIENTE)
        {
            var fECHA_FACTURAParameter = fECHA_FACTURA.HasValue ?
                new ObjectParameter("FECHA_FACTURA", fECHA_FACTURA) :
                new ObjectParameter("FECHA_FACTURA", typeof(System.DateTime));
    
            var iNFORME_VENTAParameter = iNFORME_VENTA != null ?
                new ObjectParameter("INFORME_VENTA", iNFORME_VENTA) :
                new ObjectParameter("INFORME_VENTA", typeof(string));
    
            var fK_CLIENTEParameter = fK_CLIENTE.HasValue ?
                new ObjectParameter("FK_CLIENTE", fK_CLIENTE) :
                new ObjectParameter("FK_CLIENTE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_AGREGAR_FACTURA2", fECHA_FACTURAParameter, iNFORME_VENTAParameter, fK_CLIENTEParameter);
        }
    
        public virtual ObjectResult<SP_CONSULTAR_FACTURA_Result> SP_CONSULTAR_FACTURA(Nullable<int> id_factura)
        {
            var id_facturaParameter = id_factura.HasValue ?
                new ObjectParameter("id_factura", id_factura) :
                new ObjectParameter("id_factura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CONSULTAR_FACTURA_Result>("SP_CONSULTAR_FACTURA", id_facturaParameter);
        }
    }
}
