//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPrueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOS_EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATOS_EMPLEADO()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int PK_ID_EMPLEADO { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string NUMERO_DOCUMENTO { get; set; }
        public Nullable<System.DateTime> FECHA_EXPEDICION { get; set; }
        public string NUMERO_CONTACTO { get; set; }
        public string CORREO_ELECTRONICO { get; set; }
        public string GENERO { get; set; }
        public Nullable<int> NUMERO_ACCESO { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO_EMP { get; set; }
        public Nullable<int> FK_ID_TIPO_DOCUMENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
