//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPrueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACT
    {
        public int PK_ID_DETALLE_FACT { get; set; }
        public Nullable<int> CANTIDAD_PRODUCTO { get; set; }
        public Nullable<double> SUBTOTAL { get; set; }
        public Nullable<double> DESCUENTO { get; set; }
        public Nullable<double> VALOR_TOTAL { get; set; }
        public Nullable<double> IVA_DETALLE_FACT { get; set; }
        public Nullable<int> FK_ID_CLIENTE { get; set; }
        public Nullable<int> FK_ID_USUARIO { get; set; }
        public Nullable<int> FK_ID_PRODUCTO { get; set; }
        public Nullable<int> FK_ID_FACTURA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual FACTURA FACTURA { get; set; }
    }
}
