//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPrueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.DETALLE_FACT = new HashSet<DETALLE_FACT>();
        }
    
        public int PK_ID_USUARIO { get; set; }
        public string USUARIO1 { get; set; }
        public string CLAVE { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public Nullable<int> FK_ID_EMPLEADO { get; set; }
        public Nullable<int> FK_ID_CARGO { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual DATOS_EMPLEADO DATOS_EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_FACT> DETALLE_FACT { get; set; }
    }
}
